model:
  config: "nn/model/deep_classification.yml"
  save_dir:

data:
  dataset: "CIFAR10"
  val_split: 0.2
  train_batch_size: 32
  val_batch_size: 128
  test_batch_size: 128
  num_workers: 8
  train_transform:
    [
      [ RandomHorizontalFlip, [] ],
      [ RandomRotation, [ 30 ] ],
      [ ColorJitter, [ 0.2, 0.2, 0.2, 0.1 ] ],
      [ Resize, [ [32, 32] ] ],
      [ ToTensor, [] ],
      [ Normalize, [ [0.5, 0.5, 0.5], [0.5, 0.5, 0.5] ] ],
    ]
  test_transform:
    [
      [ Resize, [ [32, 32] ] ],
      [ ToTensor, [] ],
      [ Normalize, [ [0.5, 0.5, 0.5], [0.5, 0.5, 0.5] ] ],
    ]

trainer:
  max_epochs: 250
  optimizer:
    type: Adam
    args:
      lr: 0.0001
      weight_decay: 0.0
