model:
  config: "nn/model/deep_classification.yml"
  save_dir:

# Read for more: https://pytorch.org/vision/main/datasets.html
data:
  dataset: "CIFAR10"
  val_split: 0.2
  train_batch_size: [128,32,2048]
  val_batch_size: 128
  test_batch_size: 128
  num_workers: 7
  train_transform:
    [
      [ Resize, [ [32, 32] ] ],
      [ ToTensor, [] ],
      [ Normalize, [ [0.5, 0.5, 0.5], [0.5, 0.5, 0.5] ] ],
    ]
  test_transform:
    [
      [ Resize, [ [32, 32] ] ],
      [ ToTensor, [] ],
      [ Normalize, [ [0.5, 0.5, 0.5], [0.5, 0.5, 0.5] ] ],
    ]

trainer:
  max_epochs: 5
  optimizer:
    type: Adam
    args:
      lr: 0.0001
      weight_decay: 0.0
